# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'SudokuScanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '5.6.0'
  pod 'OpenCV', '4.3.0'
  pod 'SwiftLint', '0.54.0'

  target 'SudokuScannerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SudokuScannerUITests' do
    # Pods for testing
  end

end

# for Mac M1
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
